---
openapi: 3.0.1
info:
  title: Rails API v1
  version: v1
paths:
  "/api/v1/books":
    get:
      summary: list books
      responses:
        '200':
          description: successful
    post:
      summary: create book
      responses:
        '200':
          description: successful
  "/api/v1/books/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show book
      responses:
        '200':
          description: successful
    patch:
      summary: update book
      responses:
        '200':
          description: successful
    put:
      summary: update book
      responses:
        '200':
          description: successful
    delete:
      summary: delete book
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
